### ISSUE TITLE
(Android) error: package com.testfairy.react does not exist

### ISSUE THREAD

**Issue by laylafy** [testfairy/react-native-testfairy#10]
I am trying to install Testfairy in both iOS and Android builds of my react-native project. The iOS worked find and I could find the session appear on my page, however I am getting an error trying to get the Android version built:

Scanning 553 folders for symlinks in <proj>/node_modules (12ms)
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...
Incremental java compilation is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:app:prepareComAndroidSupportRecyclerviewV72340Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42340Library UP-TO-DATE
:app:prepareComFacebookFbuiTextlayoutbuilderTextlayoutbuilder100Library UP-TO-DATE
:app:prepareComFacebookFrescoDrawee0110Library UP-TO-DATE
:app:prepareComFacebookFrescoFbcore0110Library UP-TO-DATE
:app:prepareComFacebookFrescoFresco0110Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipeline0110Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineBase0110Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineOkhttp30110Library UP-TO-DATE
:app:prepareComFacebookReactReactNative0420Library UP-TO-DATE
:app:prepareComFacebookSoloaderSoloader010Library UP-TO-DATE
:app:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:app:prepareTestfairyTestfairyAndroidSdk1413Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:mergeDebugShaders UP-TO-DATE
:app:compileDebugShaders UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:bundleDebugJsAndAssets SKIPPED
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:app:compileDebugJavaWithJavac
:app:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
<proj>/android/app/src/main/java/com/hello/MainApplication.java:14: error: package com.testfairy.react does not exist
import com.testfairy.react.TestFairyPackage; // import package

I've already modified both settings.gradle and build.gradle according to https://docs.testfairy.com/Platforms/React_Native.html and tried ./gradlew --refresh-dependencies with no success. 

Any idea what the issue might be?

**Comment by vijaysharm** [comment]
Hi @mhmdfy That's very weird. The only reason to get that error is that java can't find the project in its classpath. I just tried this using the following versions of react-native
```
react-native-cli: 2.0.1
react-native: 0.42.0
```

and I don't have that problem. Can you confirm that the path you added to the settings.gradle exists? Specifically this line:
```
include ':react-native-testfairy'
project(':react-native-testfairy').projectDir = new File(settingsDir, '../node_modules/react-native-testfairy/android')
```
make sure that that the path you have there is correct **from the perspective of settings.gradle**. Could you share the output of the path `android/app/build/intermediates/exploded-aar/` if you see both `testfairy` and `TestFairyReactNative` then that means that the libraries have been correctly added, and perhaps you would need to clean and rebuild for gradle to pick up the libraries.

**Comment by laylafy** [comment]
Hello vijaysharm,
Thanks for your quick reply. I have these files in android/app/build/intermediates/exploded-aar/:
```
com.android.support
com.facebook.fbui.textlayoutbuilder
com.facebook.fresco
com.facebook.react
com.facebook.soloader
org.webkit
testfairy
```

So I can see testfairy but TestFairyReactNative doesn't seem to be there. The content of android/settings.gradle:
```
rootProject.name = 'Hello'

include ':app'

include ':react-native-testfairy'
project(':react-native-testfairy').projectDir = new File(settingsDir, '../node_modules/react-native-testfairy/android')
```

As I said before, I tried ./gradlew --refresh-dependencies and didn't work. Is there another way to rebuild/refresh them?

**Comment by vijaysharm** [comment]
Thats quite bizarre. Can you confirm that `TestFairyModule.java` and `TestFairyPackage.java` exist in the directory `node_modules/react-native-testfairy/android/src/main/java/com/testfairy/react/`? If they do indeed exist, then I'm sincerely at a loss.

An option would be to move those two files in to your own `android/app/src/main/java/com/testfairy/react/` path, and see if that solves this issue, but I honestly don't have any idea why you're having this problem.

Can you reproduce this problem in a sample project that you can send to me, so I hope to reproduce it on my end?

**Comment by laylafy** [comment]
The two java files do exist in `node_modules/react-native-testfairy/android/src/main/java/com/testfairy/react/` but after copying them to the newly created `android/app/src/main/java/com/testfairy/react/` directory it does work.

What do you think the issue is? It seems that for some reason it doesn't see the files in the correct location, so is the issue with settings.gradle? How do you think I should fix it?

While it does work now, I feel disorganized having library files in my main directory and would rather keep them where they belong.  Nevertheless, I thank you for your time!

**Comment by vijaysharm** [comment]
Hi @mhmdfy i agree, the solution is less than ideal, and I just wanted to confirm that the npm package is indeed downloading all the right files.

I'm sincerely not sure what's happening here. I find it weird that gradle found `testfairy` (which are the core sdk classes) in `android/app/build/intermediates/exploded-aar/` but not `TestFairyReactNative` (which are the wrapper classes around the core sdk).  If you checkout `https://github.com/testfairy/react-native-testfairy/blob/master/android/build.gradle`, you can see that dependency. So i find it weird that gradle was able to determine to pick up the core sdk and not the wrapper class around it. Could it be your project adds the core SDK directly? The way I set up my sample is by editing my android/app/build.gradle with the following line
```
compile project(path: ':react-native-testfairy')
```
You don't have a line like `compile 'testfairy:testfairy-android-sdk:1.4.5'` any where in your project right?

**Comment by laylafy** [comment]
Not specifically 1.4.5, but I do have that line in app/build.gradle:

```
dependencies {
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile 'testfairy:testfairy-android-sdk:1.+@aar' // TestFairy
}
```

I did that following https://docs.testfairy.com/Android/Integrating_Android_SDK.html. Could that be the issue?

**Comment by laylafy** [comment]
So I just replaced the line `compile 'testfairy:testfairy-android-sdk:1.+@aar'` with `compile project(path: ':react-native-testfairy')` and removed the new `android/app/src/main/java/com/testfairy/react/` directory that was added before and it seems to be working.. 

Such a minor problem caused all that headache. Regardless, thanks a lot for your help!

**Comment by vijaysharm** [comment]
Good to hear! I'll consider this issue closed.

Cheers!
