### ISSUE TITLE
Getting error when running 'react-native run-android'

### ISSUE THREAD

**Issue by andreechristian** [testfairy/react-native-testfairy#11]
`* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-testfairy'.
      > The SDK Build Tools revision (23.0.2) is too low for project ':react-native-testfairy'. Minimum required is 25.0.0`

Could you guys help me on this?

**Comment by vijaysharm** [comment]
It appears you've set your project's minimum to 25. You should pick a lower version.

**Comment by andreechristian** [comment]
Sorry, i am really new at this. What is the recommended version and how could i change it?

**Comment by vijaysharm** [comment]
I guess that's a bit of a business decision. your min should be equal to whatever version your app needs feature wise/support wise. OR if you really want to support v25, fork this repo, set change the minimum to 25 and profit!

**Comment by andreechristian** [comment]
I see, thanks for your help!

**Comment by Rambatino** [comment]
I don't think it's necessarily a 'business decision'. You should aim to use the most recent stable version you can. Otherwise you'll need to update due to bugfixes or due to the requirement of new features at a later point in time. That said, you guys should really try and support version 25, it sucks that I have to drop my version by two majors to enable this library.

**Comment by gmegidish** [comment]
The requirement for version 23 is only for the build tools. It does not affect the target or minimum API level your app supports. Please just run the `sdk manager` and add build tools for version 23. Any other version would cause similar problems for whoever doesn't have the tools available. 

As a developer of an SDK, it's important to us that when somebody has managed to compile their project successfully, we don't change versions and break their compilation without them knowing. So please just install build tools 23 and you should be okay :)
