### ISSUE TITLE
How can I customize my feedback behaviour for android ?

### ISSUE THREAD

**Issue by apurvajain** [testfairy/react-native-testfairy#13]
I am trying to do something of this sort -> https://docs.testfairy.com/Android/Customizing_feedback_dialog.html

But  don't see a way to do it via this module? Can someone please help

**Comment by yairba** [comment]
Hi @apurvajain 
What exactly are you trying to do?
Can you please email us to support at testfairy dot com?
Thanks!

**Comment by apurvajain** [comment]
@yairba I have tried email multiple times from our enterprise account but did nit get any response.

What I am trying to achieve?
I have made a react native application, the app is uploaded to testfairy. We need to collect a feedback from our testers in form a multiple choice questionnaire. 
Which is available as an option in android SDK -> https://docs.testfairy.com/Android/Customizing_feedback_dialog.html

I want to do similar stuff but via react native testfairy bridge.

Please help me. Thanks in advance.
