### ISSUE TITLE
I do not want to package the library in production enviornment

### ISSUE THREAD

**Issue by Reiji87** [testfairy/react-native-testfairy#15]
Is there anyway to remove the library if I am building binary for both android/ios? 

I do not want to include test-fairy when I deploy my code in the playstore/appstore

I can't seem to get a easy way to do that

**Comment by vijaysharm** [comment]
@Reiji87 thank you for your question. I'm not sure if react native supports this out of the box, and isn't something any library can do as part of its npm package. I believe you will have to get down and dirty into your android and ios build project files, and create new flavors and schemes respectively, add the libraries you want for the specific flavor/scheme and then tell react native to build the appropriate  flavor/scheme based on the release type (debug vs production)
