### ISSUE TITLE
can't build release target - link error

### ISSUE THREAD

**Issue by sginn** [testfairy/react-native-testfairy#16]
My environment:
react-native-testfairy @ 2.6.0
react-native: 0.51
xcode: 9.2
npm: 5.5.1
node: 8.9.1

Steps taken:
```
npm install react-native-testfairy
react-native link
```
From there, I have tweaked my fastlane 'beta' config, to publish to testfairy.
```
fastlane beta
```

The build fails with a linker error, unable to find ReactNativeTestFairy.
In XCode I get the same issue, If I target "Generic iOS Device", the build fails with
 `ld: library not found for -lReactNativeTestFairy`

Crawling through my build output, the test fairy project isn't building.  For reasons I don't understand, xcode is not recognizing it as an implicit dependency.

If I add the dependency myself, things seem to be working:
- Select my app project
- select build phases
- under Target Dependencies, add ReactNativeTestFairy

Both produce archive, and going back to `fastlane beta` start working

One note: if you do this and try to just build in xcode as is, you might start getting a bitcode error.  If you produce an 'archive' or switch the configuration to Release, that won't happen.

**Comment by lucasbento** [comment]
@vijaysharm: can you take a look at this? I'm experiencing the same with version `2.6.0`.

**Comment by vijaysharm** [comment]
Hi, thank you for reporting this issue. we're actively looking into this, and will create a new release once its been resolved.

**Comment by vijaysharm** [comment]
After some investigation, it appears that the issue was the xcproject root thought it was a macOS project instead of an iOS project. I've created a new release v2.7.0 which should address this issue. Please upgrade and give it a try. I'll close this issue, please feel free to reopen it if you continue to see problems.
