### ISSUE TITLE
Can you please add targetSdkVersion

### ISSUE THREAD

**Issue by mymail4blogs** [testfairy/react-native-testfairy#23]
Google Play requires that apps target API level 26 or higher

**Comment by jigaryadav** [comment]
Those who are getting error like this 
![screenshot 2019-02-24 at 10 38 04 pm](https://user-images.githubusercontent.com/22216148/53303277-7cb10c00-388e-11e9-9b2f-8e9b91951641.png)

please go into the node_modules/react-native-testfairy/android/build.gradle and change the minimum sdk version form 23 to 26

**Comment by vijaysharm** [comment]
Ask and ye shall receive. v2.18.2. Sorry about the long wait, totally my fault.
