### ISSUE TITLE
duplicate declaration of method 'disableFeedbackForm'

### ISSUE THREAD

**Issue by jimmydjabali** [testfairy/react-native-testfairy#24]
https://github.com/testfairy/react-native-testfairy/blob/0b1981ead2b629664beeaf896f9f874919aa004d/ios/RCTTestFairyBridge.m#L182

I think you guys writes something's wrong..
I guess it should be
`RCT_EXPORT_METHOD(disableAutoUpdate) {`

instead of
`RCT_EXPORT_METHOD(disableFeedbackForm) {`

**Comment by vijaysharm** [comment]
Thanks for letting us know @MisterFail. I've fixed the issue and pushed a new release, it should be out (v2.19.2) within the hour. 

https://github.com/testfairy/react-native-testfairy/commit/5831653ebf85887b52ae9a2260a899d2dc2b2c37

Cheers
