### ISSUE TITLE
Auto update not working on iOS

### ISSUE THREAD

**Issue by KolenkoJan** [testfairy/react-native-testfairy#25]
I followed the steps on testfairy website and checked auto-update in settings - app distribution. iOS is not prompting auto update for newer versions while android is.

**Comment by vijaysharm** [comment]
Hi @KolenkoJan I just tried this, and seems to be working for me. Are you testing on a simulator? Auto update will not working in a simulator.

Can you please give more information regarding your environment? Which version of react native are you using, specifically which version of our library are you using, what device you're testing on, etc.. 

If possible, you can send a follow up email to support@testfairy.com so we can keep a history of the conversation.

**Comment by KolenkoJan** [comment]
I already contacted TestFairy support team, they responded to be aware of the issue and are working on it. In this case I'm closing this conversation.
