### ISSUE TITLE
Incompatible with react native 0.61

### ISSUE THREAD

**Issue by Sly777** [testfairy/react-native-testfairy#27]
hey all,

We tried to upgrade our app from rn 0.59 to 0.61 but there is memory leak on video recording on iOS (it works well on android). We disabled the video recording to continue with this.

bug info from bugsnag (which means nothing, unfortunately)
```
Out Of Memory - unknown method
The app was likely terminated by the operating system while in the foreground
```

phone info:
```
model: iPhone SE
osVersion: 13.0
runtimeVersions: {
  "osBuild": "17A577"
}
simulator: false
```

We are using the latest react-native-testfairy library.

**Comment by vijaysharm** [comment]
Thank you @Sly777 for submitting this issue. I'm actively looking into this, and I'm unable to reproduce this issue. Can you see this issue using Xcode instruments? Does this only happen with RN 0.61?

**Comment by Balasnest** [comment]
@Sly777 May I know what was the issue? It's happening the same for me after upgrading react native.
