### ISSUE TITLE
Android React Native build support?

### ISSUE THREAD

**Issue by 0xc1c4da** [testfairy/react-native-testfairy#3]
Is there support on the roadmap for this plugin? or is there a better route?

**Comment by hiradyazdan** [comment]
+1 :+1:

**Comment by vijaysharm** [comment]
Ask and ye shall receive: https://github.com/testfairy/react-native-testfairy/pull/4

Note that i've earmarked the release as 2.0.0, and there is a small migration required if you're hiding views. See README for more information.

**Comment by hiradyazdan** [comment]
awesome thanks :+1:
