### ISSUE TITLE
Export Archive Failed on Xcode 11.5

### ISSUE THREAD

**Issue by lkwjohn** [testfairy/react-native-testfairy#30]
Hey guys,

After upgrading Xcode to 11.5, we encountered the issue below when doing export archive:

- Our react-native-test-fairy is have also upgraded to 2.26.1
- our react-native is however at 0.59 

**Error:**
Assertion failed: Expected 5 archs in otool output:
Archive : /var/folders/vw/rhd99z392p33170yjl72j3vw0000gn/T/XcodeDistPipeline.~~~1bFUDF/Root/Payload/pnative.app/testfairy/libTestFairy.a
/var/folders/vw/rhd99z392p33170yjl72j3vw0000gn/T/XcodeDistPipeline.~~~1bFUDF/Root/Payload/pnative.app/testfairy/libTestFairy.a(TFFeedbackDrawView.o):

**Comment by vijaysharm** [comment]
Hi @lkwjohn thanks for reporting this issue. I just got around to trying this on my end, but I can't seem to reproduce this issue. I see you've since closed it the issue. Would you mind sharing what exactly happened and how you managed to resolve the issue (assuming you've resolved it?)
