### ISSUE TITLE
jetified / fastlane / react-native-testfairy

### ISSUE THREAD

**Issue by rares-lupascu** [testfairy/react-native-testfairy#31]
Hi

I honestly do not know where this error comes from but I can tell you that a normal build works, assembleRelease works but when deployed using fastlane I get this:

```javascript
Execution failed for task ':react-native-testfairy:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > 1 exception was raised by workers:
     com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
     /Users/wowzaaa/.gradle/caches/transforms-2/files-2.1/10c11b412b4d82ea97f11ba6fcb3bfa5/jetified-react-native-0.62.2/res/values/values.xml:143:5-148:13: AAPT: error: style attribute 'attr/windowActionBar (aka com.testfairy.react:attr/windowActionBar)' not found.
```

any idea on how to approach this?

thanks,
Rares

**Comment by vijaysharm** [comment]
Hi @rares-lupascu thanks for raising this issue. This is the first we've heard of this, so we'll have to investigate. Do you have a sample project we could fork to help us reproduce this issue?

**Comment by rares-lupascu** [comment]
unfortunately, it is a private app and I cannot give u access to it :(
from what I see it might be related to the androidX + fastlane + react-native-testfairy mix

**Comment by Panda-ref** [comment]
I think we have a similar problem.
react-native 0.59.10
react-native-testfairy 2.27.0

```
* What went wrong:
Execution failed for task ':react-native-testfairy:verifyReleaseResources'.
> 1 exception was raised by workers:
com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
error: resource style/Theme.AppCompat.Light.Dialog (aka com.testfairy.react:style/Theme.AppCompat.Light.Dialog) not found.
error: resource style/Theme.AppCompat.Light.Dialog (aka com.testfairy.react:style/Theme.AppCompat.Light.Dialog) not found.
error: resource style/Theme.AppCompat.Light.Dialog (aka com.testfairy.react:style/Theme.AppCompat.Light.Dialog) not found.
error: resource style/Theme.AppCompat.Light.Dialog (aka com.testfairy.react:style/Theme.AppCompat.Light.Dialog) not found.
error: resource style/Theme.AppCompat.Light.NoActionBar (aka com.testfairy.react:style/Theme.AppCompat.Light.NoActionBar) not found.
/var/jenkins_home/workspace/***/node_modules/react-native-testfairy/android/build/intermediates/res/merged/release/values/values.xml:102: error: style attribute 'attr/windowActionBar (aka com.testfairy.react:attr/windowActionBar)' not found.
error: failed linking references.
```

contents of values.xml if it helps
```
   100	    <style name="Theme.ReactNative.AppCompat.Light.NoActionBar.FullScreen" parent="@style/Theme.ReactNative.AppCompat.Light">
   101	        <item name="android:windowNoTitle">true</item>
   102	        <item name="windowActionBar">false</item>
   103	        <item name="android:windowFullscreen">true</item>
   104	        <item name="android:windowContentOverlay">@null</item>
   105	    </style>
```

**Comment by Panda-ref** [comment]
@vijaysharm 
I see your Travis config runs
`"./gradlew assembleDebug"`
before every build which is fine but doesn't prove real-world usage
`"./gradlew assembleRelease"`
that fails 100% in your current master. Just tried it myself with a docker setup.
We can consider this as a sample project.

I cloned this repo and tried all the versions down to 2.26.0 which was the last one before
`api 'com.facebook.react:react-native:0.20.1'` was changed to `api 'com.facebook.react:react-native:0.+@aar'` and it works with your travis.yml config for `assembleRelease` scenario.

**Comment by rodgomesc** [comment]
same problem here, with 0.60.5

**Comment by RafiMichaeli** [comment]
Hi, Im rafi from the testfairy support team. Just wanted to let you know we have stopped supporting react native less than version .60 (july 2019) so we recommend to upgrade your react native installation to version .60 or over.

**Comment by rares-lupascu** [comment]
still happening on RN 0.63.2

when compiling using fastlane:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-testfairy:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > 1 exception was raised by workers:
     com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
     /Users/wowzaaa/.gradle/caches/transforms-2/files-2.1/c764bd06b4b480283042bbd88d951243/jetified-react-native-0.63.2/res/values/values.xml:144:5-149:13: AAPT: error: style attribute 'attr/windowActionBar (aka com.testfairy.react:attr/windowActionBar)' not found.
```

all works fine when run locally

**Comment by mtettmar** [comment]
Same problem here with RN0.63.1 and react-native-testfairy:2.29.0

**Comment by vijaysharm** [comment]
Hi all, thanks for letting us know. We're still actively looking into this. I tried replacing `./gradlew assembleDebug` with ` ./gradlew assembleRelease` and didn't see the issue. Is this issue specific to having fastlane enabled? Can someone point to the last working version?

**Comment by rares-lupascu** [comment]
@vijaysharm I think the important factor here is Fastlane ... at least for me ...
I run apps locally with XCode and Android Studio and they both work

fastlane ios => works
fastlane android => error ... the one above
```
AAPT: error: style attribute 'attr/windowActionBar (aka com.testfairy.react:attr/windowActionBar)' not found.
```

so if u are trying to replicate I think Fastlane needs to be included in the test

**Comment by mtettmar** [comment]
@rares-lupascu - I'm not using Fastlane. Yes they work locally in debug mode. It's when building for production with assembleRelease that the issue occurs. It may be minify related but I tried ignoring the testfairy class in proguard-rules and still got the issue.

**Comment by vijaysharm** [comment]
Hi all, I think I managed to solve the issue with release 2.29.1. It looks like our wildcard dependency on the react-native android library was outdated.

I'll mark the issue closed unless someone is still seeing this issue.

I want to thank everyone for helping out on this one!

**Comment by rares-lupascu** [comment]
confirmed ... worked for me 👍
