### ISSUE TITLE
TestFairy.hideView() not working

### ISSUE THREAD

**Issue by vinodf2f** [testfairy/react-native-testfairy#33]
We have integrated testfairy in our application and we are getting an issue with hideview.
The implementation is quite simple nothing complex.
Please find the code below. Also attaching screenshot of the error message we are getting.

Also [docs](https://docs.testfairy.com/SDK/Hiding_Sensitive_Data.html#react-native) seems to be using deprecated method of assigning refs.

We are using -
  "react": "16.13.1",
   "react-native": "0.62.2",
   "react-native-testfairy": "^2.32.1",

Platform IOS 
<img width="206" alt="Screenshot 2020-09-25 at 2 54 20 PM" src="https://user-images.githubusercontent.com/41716058/94250670-26f78680-ff3f-11ea-81a4-d38a8b342b4d.png">

Platform Android
<img width="275" alt="Screenshot 2020-09-25 at 2 47 36 PM" src="https://user-images.githubusercontent.com/41716058/94249865-1abef980-ff3e-11ea-91ae-05d061b65fe2.png">

> export default class Onboarding extends Component {
>   componentDidMount() {
>     TestFairy.hideView(this.rerref);
>   }
>   render() {
>     return (
>       <View
>         style={{flex: 1, backgroundColor: 'white'}}
>         ref={(ref) => (this.rerref = ref)}>
>         <View style={{flex: 1, backgroundColor: 'red'}} />
>       </View>
>     );
>   }
> }

@vijaysharm

**Comment by vijaysharm** [comment]
Hi. Thanks for letting us know. I'll have a look and get back to you.

**Comment by vijaysharm** [comment]
Hi @vinodf2f, can you try using `nativeID` instead to see if that works for you? Although I didn't get the same error, I noticed that nativeID seemed to work for me. If so I'll update the docs so they recommend using nativeID instead.

**Comment by vinodf2f** [comment]
Hey @vijaysharm , It worked for us .
Thank you .
