### ISSUE TITLE
Incompatible with iOS Simulator on M1 Mac with Expo SDK 43 

### ISSUE THREAD

**Issue by shoes22** [testfairy/react-native-testfairy#42]
This issue comes from `libTestFairy.a`. When trying to compile on a Mac M1 to run on the iOS simulator, `building for iOS Simulator, but linking in object file built for iOS, file 'libTestFairy.a' for architecture arm64`. 

This problem is for M1 Macs, the iOS simulator runs natively on M1 and is not x86-64 emulated. However libTestFairy.a does not support the apple-arm-simulator. 

Previously, this issue had a workaround by excluding arm64 from simulator builds, but that is no longer a viable solution, as expo-modules-core in Expo SDK 43 does not build for the x86-64 simulator on M1 with the prebuilt module.

The easiest thing is to allow `libTestFairy.a` to work against the `arm64-apple-ios-simulator` architecture.

**Comment by vijaysharm** [comment]
Thanks @shoes22 for brining this to our attention. Unfortunately, currently, there are limitations with adding an arm64-simulator build to a static library. We do currently have an xcframework that works with M1 Macs that we deploy through Swift Package manager, however, the react native plugin is not using that framework.

Again, thanks for bringing this to our attention, and it's something we'll look into resolving, hopefully in the near future.

**Comment by rahul-singh-solanki** [comment]
I am facing the same issue. Due to `react-native-testfairy` I am unable to run the project on M1 (without resseta). It will be great if someone please have look at this issue.
Thanks in advance 💯

**Comment by SConaway** [comment]
Hey there, it's been almost 2 months, and this is still an issue. With the release of the new MacBooks, more and more developers are going to have Apple Silicon Macs and this is going to get worse. Using Rosetta isn't a solution but merely a workaround that isn't ideal. Is it possible to elaborate on what needs to be done?

**Comment by shoes22** [comment]
Any update on this? We've been continuing to use Rosetta and compiling x86_64 for the simulator, but being able to properly benchmark performance on the simulator it's imperative we get this running on the native architecture.

**Comment by samkhan17** [comment]
I am also facing the same issue. Developers are using M1 now. This needs to be fixed immediately.

**Comment by jmunckhof** [comment]
Same issue here, any updates on this?

**Comment by vijaysharm** [comment]
Hi, this should be resolved with version 2.62.0. Its now using an XCFramework instead of the static library. I will close this ticket. please reopen if upgrading does not work for you.
