### ISSUE TITLE
Could not resolve com.testfairy:testfairy-*******-sdk:1.12.27

### ISSUE THREAD

**Issue by samkhan17** [testfairy/react-native-testfairy#46]
Hi, I'm facing this issue, can anyone please look into this on priority. 

<img width="1050" alt="Screenshot 2022-09-07 at 6 39 00 PM" src="https://user-images.githubusercontent.com/108513091/188886447-fb68fb47-91ea-4743-b449-bba6d54c6fd6.png">

**Comment by vijaysharm** [comment]
Hi @samkhan17 thanks for reporting this. We'll investigate and get back to you. 🍻

**Comment by vijaysharm** [comment]
Hi, could you try again? It appears the issue has resolved itself.

**Comment by samkhan17** [comment]
It works now. Thanks
