### ISSUE TITLE
ld: library not found for -lTestFairy error for ios

### ISSUE THREAD

**Issue by cervebar** [testfairy/react-native-testfairy#49]
Hi Testfairy team,
I'm trying to integrate SDK ("react-native-testfairy": "^2.61.0") to our React Native project but I'm not able to build it.

I'm using React native (v 0.68) so I followed this tutorial: [https://docs.testfairy.com/ > React Native > Automatic Installation ](https://docs.testfairy.com/Platforms/React_Native.html). Only change is that I'm using `yarn`.

Then I'm trying to build my project for iOS (`react-native run-ios`) and the:
```
❌  ld: library not found for -lTestFairy
❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
error is raised.
```
<img width="638" alt="Screenshot 2023-02-13 at 13 51 57" src="https://user-images.githubusercontent.com/2403914/218463153-fb6578ad-c7f3-44c5-a0a2-abf98a59cba8.png">

I was able to reproduce this issue on smallest simple project (skipping setup of envs, Java, etc.).

Steps to reproduce:
```
# init clean project with version 0.68
npx react-native init ProjectName --version 0.68.2 
cd ProjectName

# verify app is working
react-native run-ios 

# add SDK
yarn add react-native-testfairy
yarn

# install pods
cd ios
pod install 
cd ..

# run ios again
react-native run-ios
```

other hints:
- tested on M1 and Intel chip (both the same problem)
- Android works fine
- certificates is ok (developer), it works without SDK correctly and in fact, because the base build doesn't work if never gets to the signing part (so I'm sure this is not the problem)
- tried from react-native-cli and Xcode: build doesn't work either way
- I can't use the manual installation as our project is build by CI then

Is there anything I'm missing? Any help welcome.

**Comment by vijaysharm** [comment]
Hi, could you try updating to version 2.62.0. Looks like there was an unnecessary flag in the podspec that caused this issue. I'll close the ticket because it should work with version 2.62.0. Please re-open the issue if you're still facing issues.
