### ISSUE TITLE
testfairy icon collision on ANdroid

### ISSUE THREAD

**Issue by 0xc1c4da** [testfairy/react-native-testfairy#5]
Testfairy attempts to merge the default android icon which clashes with our ic_launcher.png's which causes our builds to fail.

**Comment by giltsl** [comment]
@jarradh Can you please upgrade to version 2.0.1, It should fix the problem.
https://github.com/testfairy/react-native-testfairy/releases/tag/2.0.1

**Comment by vijaysharm** [comment]
The problem was with travis which didn't release to npmjs.

pushed manually. Closing issue.
