### ISSUE TITLE
2.0.1 package still references 2.0.0

### ISSUE THREAD

**Issue by 0xc1c4da** [testfairy/react-native-testfairy#6]
The 
https://github.com/testfairy/react-native-testfairy/releases/tag/2.0.1
release still references 2.0.0 in package.json

also  npmjs.org is still referencing 2.0.0

**Comment by vijaysharm** [comment]
hi @jarradh looks like travis failed to push 2.0.1 to npmjs. thanks for pointing that out to us!

**Comment by vijaysharm** [comment]
@jarradh updated npmjs. please let us know if you have any more problems.

Closing issue.
