### ISSUE TITLE
ld: library not found for -lTestFairy

### ISSUE THREAD

**Issue by braco** [testfairy/react-native-testfairy#8]
```
ld: library not found for -lTestFairy
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Followed iOS instructions, am getting this.

Also, any plans to support `react-native link` for ios?

**Comment by braco** [comment]
Fixed, 

followed instructions on the dedicated iOS page,
https://docs.testfairy.com/iOS_SDK/Integrating_iOS_SDK.html

The important part was probably clicking options and selecting "copy files if needed"

Docs in react-native section should probably be updated

**Comment by vijaysharm** [comment]
Thanks @braco Updated the docs.

**Comment by vijaysharm** [comment]
@braco I'm not familiar with `react-native link`. I'll definitely have a look.
