### ISSUE TITLE
undefined is not an object (evaluating TestFairyBridge.begin)

### ISSUE THREAD

**Issue by braco** [testfairy/react-native-testfairy#9]
<img width="301" alt="screen shot 2016-12-19 at 1 30 41 pm" src="https://cloud.githubusercontent.com/assets/2449172/21324344/6053b79c-c5ef-11e6-9e53-0cbe6b4a25fc.png">

Getting this from a fresh install and this invocation,

```
    componentWillMount() {
      TestFairy.begin(id);
    }
```

**Comment by braco** [comment]
Adding and removing RCTTestFairyBridge.* from the ios folder seemed to fix

**Comment by reinisriekstins** [comment]
Having exactly the same problem, however removing and adding RCTTestFairyBridge.h and RCTTestFairyBridge.m files from either `./ios/ios` (the ios folder that should be dragged into the xcode project) or `./node_modules/react-native-testfairy/ios` doesn't seem to work.

Could you explain in more detail how to fix this?

Dependency versions:
```
"react-native": "0.43.3",
"react-native-testfairy": "^2.1.4",
```
